spring.application.name=git
# Defines the unique name of this Spring Boot application that will be registered in the Eureka service registry.

eureka.instance.ip-address=true
# Configures Eureka to register this service using its IP address instead of the hostname for service identification.

eureka.client.fetch-registry=true
# Enables the client to fetch the registry information from the Eureka Server to discover other registered services.

eureka.client.register-with-eureka=true
# Allows this application to register itself as a service instance with the Eureka Server.

eureka.client.service-url.defaultZone=http://localhost:8989/eureka
# Specifies the URL of the Eureka Server where this application will register and fetch the service registry.
